### ISSUE TITLE
Add options to disable the folding animation and opacity (two separate options)

### ISSUE THREAD

**Issue by dziudek** [GavickPro/Portfolio-Free-WordPress-Theme#10]

**Comment by Nemeliom** [comment]
Hi, I can't get the animation for each post on the home page to work. My pictures look static. Can you please tell me how to enable it? Thanks

**Comment by Nemeliom** [comment]
Please check http://www.pecco.com.ar/ for further reference

**Comment by dziudek** [comment]
Which browser are you using? For me the animations are working fine.

**Comment by Nemeliom** [comment]
Hi, I've tried with both IE and Chrome. When I refer to animations I mean when you hover over the images for each post... Thank you!

**Comment by dziudek** [comment]
It seems that you didn't specified the featured image and the theme is loading the overlay directly with the post content.

**Comment by Nemeliom** [comment]
So what am I doing wrong? Sorry but I still don't get it... How should I write my posts?

**Comment by dziudek** [comment]
You should put your post image as a featured image and remove it from the post content. More: http://www.wpbeginner.com/beginners-guide/how-to-add-featured-image-or-post-thumbnails-in-wordpress/
