### ISSUE TITLE
Tag

### ISSUE THREAD

**Issue by sjikkerdennis** [GavickPro/Portfolio-Free-WordPress-Theme#14]
Hello,

i like to change the following code:

<?php
			$tag_list = get_the_tag_list('<ul class="tags-links"><li>',', </li><li>','</li></ul>');
			if ($tag_list) {
				echo $tag_list;
			}
		?>

I'd like to get the title from the post in this section. Is that possible?

**Comment by piotrkunicki** [comment]
Hi,

Yes, it's possible, try to edit content-archive.php file and change this fragment (first):
```php
<?php
			$tag_list = get_the_tag_list('<ul class="tags-links"><li>',', </li><li>','</li></ul>');
			if ($tag_list) {
				echo $tag_list;
			}
		?>
```
with:
```php
<ul class="tags-links"><li><?php the_title(); ?></li></ul>
```
