### ISSUE TITLE
Animated "read more"

### ISSUE THREAD

**Issue by gaarysn** [GavickPro/Portfolio-Free-WordPress-Theme#18]
How to remove animation "read more" on images? Or could you add option in setting?

Sory for my English...

**Comment by piotrkunicki** [comment]
Hi,

Please try to disable "Use Scroll Reveal" option from Appearance -> Customize and Layout & Features section.

**Comment by dziudek** [comment]
It needs a more complex changes - I will add it in the v.1.3 version of the theme.

**Comment by gaarysn** [comment]
Thanks, dziudek :)

**Comment by dziudek** [comment]
Done: https://github.com/GavickPro/Portfolio-Free-WordPress-Theme/commit/edd6cff286ad49256f1c92f8c441163a4f8c3f44
