### ISSUE TITLE
Next / Previous Article

### ISSUE THREAD

**Issue by bcgm3** [GavickPro/Portfolio-Free-WordPress-Theme#19]
Hello, love this theme, it's just what I'm looking for! One small thing: is there a way to add "previous post" and "next post" buttons when in single-post view? As it is, one clicks on a post to see more info, then must click "back" and select another post from the list. It would be nice to be able to cycle through all the posts in the current category with "previous" and "next" buttons. 

Thanks!

**Comment by piotrkunicki** [comment]
Hello,

You can add next, previous posts links into Portfolio/content-archive.php file (around line 37, after tags) or into content-footer.php file. Please check the following articles:
http://codex.wordpress.org/Function_Reference/previous_posts_link
http://codex.wordpress.org/Function_Reference/next_post_link

**Comment by bcgm3** [comment]
Thanks! I ended up adding the template tags from:
http://codex.wordpress.org/Function_Reference/previous_post_link (post, but not posts) and
http://codex.wordpress.org/Function_Reference/next_post_link
to the file named "Single Post" (Portfolio/single.php).
