### ISSUE TITLE
Change Google Font

### ISSUE THREAD

**Issue by fannyelise** [GavickPro/Portfolio-Free-WordPress-Theme#23]
Hello, I was wondering if anyone could help me in how I change from one Google font to another? When I try and copy the url from the google fonts website it doesn't update it in the wordpress theme, instead it becomes a default font looking a bit like Times New Roman. 

Thank you so much for your help!
Best
Fanny

**Comment by piotrkunicki** [comment]
Hello,

Please add the google font link in this format:
```
//fonts.googleapis.com/css?family=Old+Standard+TT:400,700
```

**Comment by fannyelise** [comment]
Thank you so much for letting me know. Is that a format that you can copy
from Google fonts? Can I adjust the size of the typography in the template
too?

Thank you so much for your help.
Best
Fanny

On Thursday, March 19, 2015, Piotr Kunicki <notifications@github.com> wrote:

> Hello,
>
> Please add the google font link in this format:
>
> //fonts.googleapis.com/css?family=Old+Standard+TT:400,700
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GavickPro/Portfolio-Free-WordPress-Theme/issues/23#issuecomment-83519248>
> .
>


-- 

*-------------------------------------*



*Fanny Wacklin Nilssonhello@fannywnilsson.com
<hello@fannywnilsson.com>fannywnilsson.com <http://fannywnilsson.com>*

**Comment by piotrkunicki** [comment]
Yes, of course, but if you have this format from google fonts:
```
<link href='http://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
```
you have to change it to:
```
//fonts.googleapis.com/css?family=Lato
```
Regarding the typography - you have to change the css to adjust size.
