### ISSUE TITLE
COntent width error

### ISSUE THREAD

**Issue by enkumber** [GavickPro/Portfolio-Free-WordPress-Theme#24]
If I modify the content width to any value I get this... Any ideea?

![screenshot from 2015-03-20 16 39 17](https://cloud.githubusercontent.com/assets/8458249/6753961/47fcae62-cf22-11e4-8b72-17f9f0b8656b.png)

**Comment by dziudek** [comment]
Hello,

Could you send me an access to your website to dziudek[at]gavick[dot]com ? Because I cannot reproduce your issue on my installation.

**Comment by dziudek** [comment]
Problem fixed with: https://github.com/GavickPro/Portfolio-Free-WordPress-Theme/commit/1840b4fcb379f17d3a82846407f9059d59d0a8f5
