### ISSUE TITLE
Possible to remove / rename / modify  "Category Archives: Photos" header (similar to index page)?

### ISSUE THREAD

**Issue by walrus1** [GavickPro/Portfolio-Free-WordPress-Theme#25]
How to create portfolio page without ("Category Archives: Photos")?

I am trying to make portfolio page similar to demo "index" page: https://demo.gavick.com/wordpress/portfolio/    ... (without the header ("Category Archives: Photos")  like "category page": https://demo.gavick.com/wordpress/portfolio/?cat=2)

Loaded the demo material - but the "index page" is not actually a "page" but a URL link to gavick.com so I can't use it as an example.  I can only recreate the "category page" which has the header.

**Comment by dziudek** [comment]
Hello,

You can remove it in the category.php file under the following line:

```php
<h1 class="archive-title"><?php printf( __('Category Archives: %s', 'portfolio'), '<strong>' . single_cat_title('', false) . '</strong>'); ?></h1>
```
