### ISSUE TITLE
Post Preview - Custom Edit of Content

### ISSUE THREAD

**Issue by walrus1** [GavickPro/Portfolio-Free-WordPress-Theme#27]
Currently, post preview (on mouseover) has "Post Title" and "first few words" of the post.

Enhancement:  Content customizable. --- User can create a tailored summary for the post (instead of automatic capture of first few lines contained within post)

**Comment by dziudek** [comment]
Hello,

Did you tried to use the Excerpt field in your post editor?

http://www.wpbeginner.com/glossary/excerpt/
