### ISSUE TITLE
Current selected submenu item not visible in dropdown menu

### ISSUE THREAD

**Issue by walrus1** [GavickPro/Portfolio-Free-WordPress-Theme#28]
On mobile screen size (menu items dropdown), selected sub-menu item text is same color as background (not visible) in current demo.

**Comment by dziudek** [comment]
Hello,

You're right, the fix is visible here: https://github.com/GavickPro/Portfolio-Free-WordPress-Theme/commit/1df3f84f5d16cd7c094be073e297c7ec41043eae

I'll release it with the v.1.3.0 update probably at the end of this week.
