### ISSUE TITLE
Changes to font options don't take effect

### ISSUE THREAD

**Issue by walrus1** [GavickPro/Portfolio-Free-WordPress-Theme#30]
When "Customize - Font options" are changed in wp-admin the changes appear in preview but do not take effect on the webpages.

**Comment by dziudek** [comment]
Hello,

Are you sure? For me it is working fine. Could you tell me your font options values?

**Comment by walrus1** [comment]
For example, I tried to change from original:

http://fonts.googleapis.com/css?family=Open+Sans:700
to
http://fonts.googleapis.com/css?family=Lato:700

**Comment by dziudek** [comment]
Sorry I cannot confirm it - for me the font is replacing correctly for both available font types.
