### ISSUE TITLE
Remove Featured Image from Post, but not the Home Page or Category Post Previews

### ISSUE THREAD

**Issue by walrus1** [GavickPro/Portfolio-Free-WordPress-Theme#31]
Is it possible to stop displaying the featured image inside posts without removing the featured image from the main pages or portfolio category post previews?

**Comment by dziudek** [comment]
Hello,

Currently it is not available, but I will add an option to do it in v.1.3.0

**Comment by dziudek** [comment]
Implementation: https://github.com/GavickPro/Portfolio-Free-WordPress-Theme/commit/6cf3d9f8bf8a9a803c8d6ccceab51051e20b5e61
