### ISSUE TITLE
Is there a way to change width of post or page content area?

### ISSUE THREAD

**Issue by walrus1** [GavickPro/Portfolio-Free-WordPress-Theme#32]
Is there a way to change the width of post or page content area?

**Comment by dziudek** [comment]
Yes, you can do it under the layouts tab in the theme customizer, but please apply this fix before: https://github.com/GavickPro/Portfolio-Free-WordPress-Theme/commit/1840b4fcb379f17d3a82846407f9059d59d0a8f5 (it will be included in v.1.3).
