### ISSUE TITLE
Shade selection

### ISSUE THREAD

**Issue by gaarysn** [GavickPro/Portfolio-Free-WordPress-Theme#35]
Could you make a light shade selection when you hover the mouse?

**Comment by dziudek** [comment]
Hello,

Could you better explain what do you want to achieve?

**Comment by gaarysn** [comment]
Something like this
https://youtu.be/sQefU4zoSPA

**Comment by dziudek** [comment]
Ok, now I understand :) We will add it in the upcoming v.1.4.0 release.

**Comment by dziudek** [comment]
I've added a small opacity and box-shadow animation as an option under the "Effects" tab in the Theme Customizer: https://github.com/GavickPro/Portfolio-Free-WordPress-Theme/commit/c37adf79bc372175a8ba68033cbd49bfc83d22a2
