### ISSUE TITLE
How to insert image/text slide effect

### ISSUE THREAD

**Issue by perina** [GavickPro/Portfolio-Free-WordPress-Theme#36]
I'm trying to resolve images on category pages not showing slide/out effect as per your demo. Only text appears in thumbnail. How do I set the image in the post please.

**Comment by piotrkunicki** [comment]
Hello,

Did you add featured images to your posts?
Please check this article:
http://www.wpbeginner.com/beginners-guide/how-to-add-featured-image-or-post-thumbnails-in-wordpress/

**Comment by perina** [comment]
:Yes, thank you, the trick is to "Set feature image" instead embedding it into the article.Regards :+1:
