### ISSUE TITLE
Social media icons

### ISSUE THREAD

**Issue by suusartist** [GavickPro/Portfolio-Free-WordPress-Theme#38]
Hey Gavick,

Thanks for your beautiful theme. I am very happy using it for my portfolio.

I was just wondering something. In the demo I see you've got some quite nice social media icons.
Maybe it's a very beginners question, but I can't seem to find how to add these icons to my page. 
Could you explain me how to do this? Am I overlooking a widget somewhere?

Thanks in advance!

Suzan

**Comment by piotrkunicki** [comment]
Hello,

Ssocial icons are created using WordPress menu, please check the navigation section from Portfolio configuration: https://www.gavick.com/documentation/wordpress-themes/wordpress-themes-configuration/portfolio-wordpress-theme-configuration

**Comment by suusartist** [comment]
Thanks for the reply, and sorry for my late answer. 

I have read the configuration page, but maybe the problem is that I never installed the demo version. I used the theme to overwritre an old theme for a website I have build already some time ago. 
In the configuration you write that the menus should already be prepared but on my page there is no sign of the social menu. I tried to recreate it myself, but can't seem to find out how to do that the right way. 
In the wordpress menu edit area I have turned on both Theme locations (Navigation Menu and Social Menu) in my current menu settings, but stil in the navigations tab of the costumize area I can choose only one option (Menu). The menu's that I do have don't give me the option to add CSS classes.

I hope you can help me a bit further.

Thanks!

Suzan

**Comment by piotrkunicki** [comment]
You have to add new menu and enable css class in the screen option, please check the description from our other theme:
https://www.gavick.com/documentation/themes-docs/writer/customize/#social-icons

**Comment by suusartist** [comment]
Tanks again! This really solved my issue.
