### ISSUE TITLE
"Comments are closed" not working

### ISSUE THREAD

**Issue by tomportfolio** [GavickPro/Portfolio-Free-WordPress-Theme#39]
Hello there,

thank you very much for your wonderful free theme.

Unfortunately, I've discovered a bug:

If you disable the comments for a page, the message "Comments are closed" is not displayed. Instead, there is jhust an empty comment box.

You can see the issue on the image attached.
![nomessage](https://cloud.githubusercontent.com/assets/11912078/7105998/82db252c-e133-11e4-9152-a4006cd5ee2a.jpg)

Best regards
Tom

**Comment by dziudek** [comment]
Hello,

Please apply this patch: https://github.com/GavickPro/Portfolio-Free-WordPress-Theme/commit/ae2821cce85813aa33237dd267aeb17cba2b4434

We will include it in v.1.4.0.

**Comment by tomportfolio** [comment]
Hey,
thanks for answering. I applied the Patch, but unfortunaletly, it still does not work. Now, the comment section totally disappeared instead of saying "Comments are closed" and therefore, the footer is way too long.

![comments](https://cloud.githubusercontent.com/assets/11912078/7167872/6db18546-e3b9-11e4-9c8e-b73f844b5c35.PNG)

**Comment by dziudek** [comment]
Could you provide an URL to your website with the footer problem?

**Comment by dziudek** [comment]
Ok, the issue appeared on subpages - there is a fix: https://github.com/GavickPro/Portfolio-Free-WordPress-Theme/commit/d2f340adcdcafbe02fae80a1da4789eec5320f13 

The text "Comments are closed" is unnecessary when there is no comments so I won't change this behaviour.

**Comment by tomportfolio** [comment]
Thanks for the fix, it works now.
