### ISSUE TITLE
gk contact | gk reservation

### ISSUE THREAD

**Issue by Asow** [GavickPro/Portfolio-Free-WordPress-Theme#41]
Hi there,
 
I'm using steak house template for my new site and I want to translate contact form and reservation. I normally go on /languages/en-GB and I can find files there, but for this two I can not find files. 
 
Contact form on page that is not gk contact I can translate, but gk contact and gk reservation I can't because there is no file in folder which I can translate.
 
What seems to be the problem in this?
 
Thanks

**Comment by dziudek** [comment]
Hello,

Please use an official support channels like our ticket system (if you bought our theme on theme forest): https://www.gavick.com/supportdesk or out forum (if you bought our theme at our website): https://www.gavick.com/forum

This is a support area only for the GK Portfolio WordPress theme.
