### ISSUE TITLE
Different width for portrait or landscape photos

### ISSUE THREAD

**Issue by enkumber** [GavickPro/Portfolio-Free-WordPress-Theme#42]
I didn't had this issue until I modified the content width. All my pictures have a maximum width of 1000. When I insert them the portrait pictures have a smaller width than the the landscape ones.

http://artandcolor.ro/2015/polina-vlad.html

**Comment by dziudek** [comment]
Hello,

I'm sorry but I don't understand - could you better explain your issue?

**Comment by enkumber** [comment]
It was my bad. The theme is ok!
