### ISSUE TITLE
Link to the older post is broken 

### ISSUE THREAD

**Issue by enkumber** [GavickPro/Portfolio-Free-WordPress-Theme#43]
It looks like the link the the older post is broken when opening the newest article:
http://artandcolor.ro/2015/polina-vlad.html

The link to the last article goes back to an article from 2014:
http://artandcolor.ro/2014/corina-claudiu.html

and it should point to http://artandcolor.ro/2015/corina-claudiu-the-wedding.html

**Comment by dziudek** [comment]
Hello,

No, all is ok - the post navigation is connected with posts in the same category - in the next version I will add an option to select if the taxonomy should be the same in the links. Currently you can fix it by removing the last TRUE param in the single.php file in lines 17-18.

**Comment by enkumber** [comment]
thank you! It works!
