### ISSUE TITLE
change the max number of squares that come up on a page

### ISSUE THREAD

**Issue by nickis1234** [GavickPro/Portfolio-Free-WordPress-Theme#44]
I would ideally like only a max of 8 squares to come up on a page. can this be customized? and in what file? I am familiar with css and js
Please advise
Much appreciated.

**Comment by piotrkunicki** [comment]
Hi,
Please check your General -> Writing settings and change "Blog pages show at most" option to 8 posts.

**Comment by nickis1234** [comment]
Perfect! thanks for your help!

Cheers,
Nicole
