### ISSUE TITLE
infinite scroll gallery

### ISSUE THREAD

**Issue by laurenmeranda** [GavickPro/Portfolio-Free-WordPress-Theme#45]
Is there a way to set up infinite scroll of the gallery of posts? Right not I can't find the place in the code where the number of posts per page.

thanks!

transactionspublication.com

**Comment by dziudek** [comment]
Hello,

Unfortunately currently it is not possible to use a 3rd party plugin as posts after loading are invisible. We will work on this feature in v.1.6.0 probably.

**Comment by laurenmeranda** [comment]
ok, thanks! Is there a way to change the number of posts that appear or even the wording from "older posts" to something else?

**Comment by dziudek** [comment]
You can change it under WordPress Reading settings - there is an option to set amount of posts visible per page.

**Comment by laurenmeranda** [comment]
I missed that. Thanks!
