### ISSUE TITLE
Can I somehow make a parent category in the menu clickable?

### ISSUE THREAD

**Issue by enkumber** [GavickPro/Portfolio-Free-WordPress-Theme#46]
I have a menu and under menu option Portofolio I have a the categories as options. The first option - wedding - is not clickable as it has subcategories. Can I do anything about this?
this is the site: http://artandcolor.ro/en

**Comment by dziudek** [comment]
Hello,

Please try to download v.1.5.1 from this repository - it contains few fixes for the main menu and probably for your issue too. Or please wait for accepting this version on the official wordpress themes repository.

**Comment by enkumber** [comment]
thank you

**Comment by enkumber** [comment]
I just downloaded and intalled it but it looks like nothing it's changed ... still the same problem. htnak you for your time

**Comment by dziudek** [comment]
Please apply this patch: https://github.com/GavickPro/Portfolio-Free-WordPress-Theme/commit/091bf6da6439d919fe285d5b9e5589abfb39bcdd

**Comment by enkumber** [comment]
Thank you! It works!

**Comment by abedolla0924** [comment]
> Cokkie low gk_startup theme does not display in mobile web until you do not accept cookies .
> 
> As I can change this and that functions as desktop?

**Comment by dziudek** [comment]
@abedolla0924 - this repository is for the Portfolio WordPress Theme only - for our premium products please write at our official forum or at our ticket system if you have bought our theme on Creative Market / Theme Forest.
