### ISSUE TITLE
Categories not clickable

### ISSUE THREAD

**Issue by alicesou** [GavickPro/Portfolio-Free-WordPress-Theme#48]
Hi - i've some problems with the categories. If you click on theme there is a notification 'not found',  despite the fact all posts been assigned with a category. How to solve this? Thank you

**Comment by dziudek** [comment]
Hello,

Could you provide me an URL to your website?

**Comment by alicesou** [comment]
Hi Tomasz,

www.f-site.nu

Thanks
Alice

Tomasz Dziuda schreef op 2015-07-20 11:10:
> Hello,
> 
> Could you provide me an URL to your website?
> 
> --
> Reply to this email directly or view it on GitHub [1].
> 
> 	*
> 
> Links:
> ------
> [1]
> https://github.com/GavickPro/Portfolio-Free-WordPress-Theme/issues/48#issuecomment-122819218

-- 
Van Gisteren - werkplaats voor historische projecten
www.vangisteren.nu

**Comment by dziudek** [comment]
Sorry but your website is in the maintenance mode so I cannot check it.

**Comment by alicesou** [comment]
Hi Tomasz,

It's online now. Thank you.


Tomasz Dziuda schreef op 2015-07-20 19:28:
> Sorry but your website is in the maintenance mode so I cannot check
> it.
> 
> --
> Reply to this email directly or view it on GitHub [1].
> 
> 	*
> 
> Links:
> ------
> [1]
> https://github.com/GavickPro/Portfolio-Free-WordPress-Theme/issues/48#issuecomment-122961627

-- 
Van Gisteren - werkplaats voor historische projecten
www.vangisteren.nu

**Comment by dziudek** [comment]
Please make sure that your .htaccess file is correctly created in the root of your wordpress installation
