### ISSUE TITLE
Image cropping

### ISSUE THREAD

**Issue by ceyhanmolla** [GavickPro/Portfolio-Free-WordPress-Theme#54]
Hello there. Photos should be 300 * 315 pixels cropped . If you use WordPress cropping system would be much better . It would be better for the home page .

https://developer.wordpress.org/reference/functions/add_image_size/

**Comment by dziudek** [comment]
Hello,

I am not sure if I understand - you can specify the photos image size under advanced settings of the theme. For different layouts the dimensions will be different, because user has a full control over the blocks dimensions.

**Comment by ceyhanmolla** [comment]
Sorry. What did I see . I fixed it now. Thank you.
