### ISSUE TITLE
Menu won't close on responsive view

### ISSUE THREAD

**Issue by alexgauvin** [GavickPro/Portfolio-Free-WordPress-Theme#57]
Hi,

I've just activated this theme and everything is working fine except for the main menu that will not close after opening on responsive view !

I'm using Chrome 48.0.2564.109 m (64-bit), but same issue with FF and Edge.

This problem was present just after install. I even did delete the whole theme and all custom CSS and reinstalled theme without success.

alexandregauvin.com

Thanks for any help here

**Comment by dziudek** [comment]
Hello,

Sorry but I cannot reproduce this issue on our test websites and your website is offline, so I cannot check the issue on your page.

**Comment by alexgauvin** [comment]
Thanks for coming back to me with my issue.

Sorry, the website was still on maintenance mode. You can now access it.

Thanks

**Comment by dziudek** [comment]
This patch should solve your issue: https://github.com/GavickPro/Portfolio-Free-WordPress-Theme/commit/5164ac030667bd5acb7462ed290a2ae7c6ef3a38

**Comment by alexgauvin** [comment]
Excellent,

thanks a lot
