### ISSUE TITLE
Gallery page

### ISSUE THREAD

**Issue by yukiitooo** [GavickPro/Portfolio-Free-WordPress-Theme#59]
Thank you very much for the offer of this theme.

In your demonstration site,
[https://demo.gavick.com/wordpress/portfolio/? page_id=65]
Navi: Features>Gallery page
![screen](https://cloud.githubusercontent.com/assets/18548064/14631968/01dc327e-0651-11e6-81ac-d3b8b4b8d1cd.jpg)

I'd like to post by the form of this page, but I can't.

Could you tell me how to do?

**Comment by dziudek** [comment]
Hello,

Please use [gallery] shortcode :)

**Comment by yukiitooo** [comment]
I could solve it.
Thank you very much!
