### ISSUE TITLE
Move homepage slideshow to another page

### ISSUE THREAD

**Issue by cbfreeman** [GavickPro/Portfolio-Free-WordPress-Theme#62]
Hi,

I love the way the front page functions with the slideshow of recent posts ,but is there a way to have that same functionality on another page. Like for example creating a new template page.

Any suggestions?

Thanks,

**Comment by dziudek** [comment]
Hi,

Are you sure that you are mentioning the proper theme? As the Portfolio theme has no slideshow on the frontpage: https://wordpress.org/themes/gk-portfolio/

**Comment by cbfreeman** [comment]
Hi Dziudek,

Sorry for the confusion - I'm speaking about the recent posts that display on the homepage with jquery animation. I tried to copy the index.php template file and create a new template but the recent posts don't display.

Thanks

**Comment by cbfreeman** [comment]
I would like to reproduce that say animation effects with recent posts on another page besides the homepage/front page. Is this possible?

**Comment by dziudek** [comment]
You can also reproduce this effect on the category, tag and archive page.

**Comment by cbfreeman** [comment]
Hum interesting - so I wonder why it didn't work when I replicated the default index.php page as a new template. Will try a new category specific page. Thanks

**Comment by cbfreeman** [comment]
oh by the way do you have a sample category page template I could check out? thx

**Comment by dziudek** [comment]
Sorry but I totally not understand your issue? Whey do you want to duplicate some files if you have to just create a category, assign items to them in the WordPress dashboard and then open it? The category is based on this file: https://github.com/GavickPro/Portfolio-Free-WordPress-Theme/blob/master/category.php

**Comment by cbfreeman** [comment]
Sorry for the confusion - I got it! Thanks for the support.
