### ISSUE TITLE
Social Icon issue

### ISSUE THREAD

**Issue by preraksola** [GavickPro/Portfolio-Free-WordPress-Theme#63]
The social icons are not visible on the top bar. In the developer console, I can see that the div is created, but it's dimensions are 778x0 (no height).

**Comment by dziudek** [comment]
Hi,

Could you provide an URL to your website with this issue?

**Comment by preraksola** [comment]
The URL is: http://rootsletsconnect.in/wordpress/

Prerak

**Comment by dziudek** [comment]
Instead of menu item class **gk-icon-fb** please use **icon-fb**

**Comment by preraksola** [comment]
Yeah, that worked!
Thanks :)
